version: '3'
services:
   web:
      build:
        context: ./
        args:
          JAR_FILE: /target/demo-0.0.1-SNAPSHOT.jar
      ports:
        - "8761:8761"
      networks:
        mynet:
          ipv4_address: 172.25.0.101
networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
